name: frontend ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 12.19.1
        uses: actions/setup-node@v3
        with:
          node-version: 12.19.1
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Installing node packages..."
      - run: npm i
      - run: echo "Node package installed"
      - run: echo "Executing lint js ..."
      - run: npm run lint:js
      - run: echo "lint js completed"
      - run: echo "Executing lint:hbs ..."
      - run: npm run lint:hbs
      - run: echo "lint:hbs completed"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 12.19.1
        uses: actions/setup-node@v3
        with:
          node-version: 12.19.1
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Installing node packages..."
      - run: npm i
      - run: echo "Node package installed"
      - run: echo "Executing test ..."
      - run: npm run test
      - run: echo "Test completed ..."