name: frontend ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.19.1]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Installing node packages..."
      - run: npm i
      - run: echo "Node package installed"
      - run: echo "Executing test ..."
      - run: npm run test
      - run: echo "Test completed ..."